
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dentis-db
    username: {db-username}
    password: { db-password }

  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true